### PR TITLE
Use an AbstractRNG to control dispatch of rand!, remove rand

### PR DESCRIPTION
**Pull request by maleadt**

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Thanks, looks much better! :) 
I'm not 100% sure what to do about `rand(GPUArray)` since I kind of like it... I'm not too worried that it's not part of the official Base interface, since Base often neglects that there are other array types... Anyways, if it really bothers you, `rand!(similar(CuArray, 10))` doesn't seem to be too bad

**Comment by maleadt** [comment]
I'm not sure either. `curand(T, ...)` is better, but we can't implement that generically. I guess `@gpu rand(T, ...)` is a good solution, but we can't just block everything on Cassette.

**Comment by maleadt** [comment]
OK, going to try that design out.

**Comment by maleadt** [comment]
OK, have a look. I went with `rand!(::Array, ...)` where possible, `curand(::T, ...)` where regular arrays would otherwise be constructed.

```
# the interface is split in two levels:
# - functions that extend the Random standard library, and take an RNG as first argument,
#   will only ever dispatch to CURAND and as a result are limited in the types they support.
# - functions that take an array will dispatch to either CURAND or GPUArrays
# - `cu`-prefixed functions are provided for constructing GPU arrays from only an eltype
```

Thoughts?

**Comment by maleadt** [comment]
CI is green, latest commit is just a comment. Taking the thumbs up on the other thread as an ACK.

**Pull request merged**
