### PR TITLE
Move JLArray to a subpackage

### PR DESCRIPTION
**Pull request by mcabbott**
RFC, this wants to move the module in `test/jlarray.jl` to be another sub-package. If registered, then this could easily be used by other packages, to run their own pseudo-GPU-tests on non-GPU hardware.

### CODE REVIEW

**Comment by maleadt** [comment]
Sounds like a good idea. CI is unhappy, the path to the subpackage should probably be added to the Manifest a la https://github.com/JuliaGPU/GPUArrays.jl/blob/58608126f73a843633d88e0bdb4b51be29d88256/Manifest.toml#L31-L35=

**Comment by mcabbott** [comment]
I'm not having much luck adding this to the manifest. If I add just it:
```
(jl_TjWlp6) pkg> dev GPUArrays
   Resolving package versions...
ERROR: `JLArrays=27aeb0d3-9eb9-45fb-866b-73c2ecf80fcb` depends on `GPUArrays`, but no such entry exists in the manifest.
```
If I add also GPUArrays to its own manifest, I get warnings
```
┌ Warning: Circular dependency detected. Precompilation will be skipped for:
│   JLArrays [27aeb0d3-9eb9-45fb-866b-73c2ecf80fcb]
│   GPUArrays [0c68f7d7-f131-5f86-a1c3-88cf8149b2d7]
└ @ Pkg.API ~/.julia/dev/julia/usr/share/julia/stdlib/v1.9/Pkg/src/API.jl:1128
```
but can run tests. This is with JLArrays also in the Project.toml of GPUArrays, i.e. it's a full-time dependency. 

Should there instead be a separate test/Manifest.toml? And if I create one, which version of Julia should I use?

Alternatively, what I thought at first is that the sub-package ought to be registered first, and only after that will the tests using it run. That would mean either 2 PRs, or leaving master broken for 3 days. But is perhaps a bad idea in terms of future updates --- any further changes to JLArrays would not be tested in the main package's tests right away, only after registration. 

Sorry have not dealt with sub-packages before, it's a bit confusing!

**Comment by mcabbott** [comment]
I should have thought of this before, but latest commit changes back to `include`-ing the file, without involving `Pkg` at all. Maybe that's the simplest way to ensure that the main package's tests always use JLArrays at the same commit.

**Comment by mcabbott** [comment]
One suggestion (from [here](https://discourse.julialang.org/t/can-someone-please-explain-the-lib-directory/84238/2?u=mkitti)) is that this could explicitly call `Pkg.develop` in the tests, like so:

https://github.com/JuliaIO/HDF5.jl/blob/7999d1a261cb1c950f026946b4405686281636da/test/runtests.jl#L4-L8

If I'm thinking right, this will give an error if the committed versions don't allow each other.

**Pull request merged**
