### PR TITLE
Add a test for reducing larger array sizes

### PR DESCRIPTION
**Pull request by maxwindiff**

### CODE REVIEW

**Comment by maleadt** [comment]
The oneAPI.jl failures looks like crash in LLVM during CPU compilation, so probably unrelated. I've restarted the job.

The failures from CI here do reproduce locally though. Did you use Julia 1.8 and ran the GPUArrays test suite through `Pkg`? I did edit `testsuite.jl` to only retain the `reductions.jl` testsuite though, to speed up reproducing.

**Comment by maxwindiff** [comment]
My bad, I was running the tests from the wrong repo, no wonder the output format looked different 😅  
Should be fixed now!

**Comment by maxwindiff** [comment]
The test crashes on Julia 1.7/1.8 + Windows, however I couldn't reproduce it on my arm64 Windows VM.

Screenshot 2023-03-08 at 23 44 15

**Comment by maleadt** [comment]
Hmm, that's weird. The arrays shouldn't be large enough to cause an OOM, right?

**Comment by maxwindiff** [comment]
Hmm it's not impossible if the tests were run on a VM with limited memory. The largest array is 5000x5000xInt8 ~= 190MB. Let me try a smaller size (that can still exercise the new code paths).

**Comment by maxwindiff** [comment]
Looks like the crash is no longer happening. The last failure seems to be some CI configuration issue.

`ERROR: SystemError: opening file "/Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-aarch64-4.0/depots/c9f52312-b528-44e4-9501-6d408762012b/dev/Metal/deps/build_ci.jl": No such file or directory`

**Comment by maleadt** [comment]
> The last failure seems to be some CI configuration issue.
> 
> `ERROR: SystemError: opening file "/Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-aarch64-4.0/depots/c9f52312-b528-44e4-9501-6d408762012b/dev/Metal/deps/build_ci.jl": No such file or directory`

Yeah Metal.jl got rid of libcmt, so I need to update downstream build instructions. I'll do that separately.

Thanks for the PR, LGTM.

**Pull request merged**
