### PR TITLE
Fix 5 arg mul!

### PR DESCRIPTION
**Pull request by haampie**
Move from 3-arg mul to 5-arg mul to make sure GPUArrays's generic mul does not steal from CuArrays.

(Btw, I could not yet test because cyclops was unreachable :( )

### CODE REVIEW

**Comment by maleadt** [comment]
Thanks!
bors try

**Comment by haampie** [comment]
There's still an issue in Julia base to work around... 

```
julia> mul!(rand(Int32, 4), rand(Int32, 4, 4), rand(Int32, 4), Int32(4), Int32(5))
ERROR: InexactError: trunc(Int32, -138749043280184131)
```

I'll update the tests here s.t. that values don't get extremely high, but I would say ^ is a bug in LinearAlgebra, because it promotes to Int64.

**Comment by haampie** [comment]
Can you retry?

**Comment by maleadt** [comment]
bors try

**Comment by maleadt** [comment]
bors d+

**Comment by haampie** [comment]
Oh sorry :/ I've tried it locally

```
Test Summary: | Pass  Total
JLArray       | 1116   1116
```

Final request to retry? :sweat_smile:

**Comment by maleadt** [comment]
After the `bors d+` you can do it yourself:
bors try

**Comment by haampie** [comment]
travis timed out

bors try

**Pull request merged**
