### PR TITLE
Add inv for Triangular types and test.

### PR DESCRIPTION
**Pull request by aterenin**
Originally wrote this for CuArrays, but realized that this can be made generic as long as `ldiv!` is available.

### CODE REVIEW

**Comment by maleadt** [comment]
bors try

**Comment by aterenin** [comment]
```julia
  Test threw exception
481  Expression: compare((x->begin
482            inv(TR(x))
483        end), AT, rand(Float32, 32, 32))
484  conversion to pointer not defined for JLArray{Float32,2}
485  Stacktrace:
486   [1] error(::String) at ./error.jl:33
487   [2] unsafe_convert(::Type{Ptr{Float32}}, ::JLArray{Float32,2}) at ./pointer.jl:67
488   [3] trtrs!(::Char, ::Char, ::Char, ::JLArray{Float32,2}, ::JLArray{Float32,2}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/LinearAlgebra/src/lapack.jl:3408
489   [4] ldiv!(::LinearAlgebra.UpperTriangular{Float32,JLArray{Float32,2}}, ::JLArray{Float32,2}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/LinearAlgebra/src/triangular.jl:656
490   [5] inv(::LinearAlgebra.UpperTriangular{Float32,JLArray{Float32,2}}) at /home/travis/build/JuliaGPU/GPUArrays.jl/src/host/linalg.jl:209
491   [6] (::Main.TestSuite.var"#242#250"{UnionAll})(::JLArray{Float32,2}) at ./none:0
492   [7] #compare#1(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(Main.TestSuite.compare), ::Function, ::Type{JLArray}, ::Array{Float32,2}, ::Vararg{Array{Float32,2},N} where N) at /home/travis/build/JuliaGPU/GPUArrays.jl/test/testsuite.jl:23
493   [8] compare(::Function, ::Type{JLArray}, ::Array{Float32,2}, ::Vararg{Array{Float32,2},N} where N) at /home/travis/build/JuliaGPU/GPUArrays.jl/test/testsuite.jl:20
494   [9] macro expansion at /home/travis/build/JuliaGPU/GPUArrays.jl/test/testsuite/linalg.jl:50 [inlined]
495   [10] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Test/src/Test.jl:1180 [inlined]
496   [11] macro expansion at /home/travis/build/JuliaGPU/GPUArrays.jl/test/testsuite/linalg.jl:49 [inlined]
497   [12] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Test/src/Test.jl:1107 [inlined]
498   [13] test_linalg(::Type) at /home/travis/build/JuliaGPU/GPUArrays.jl/test/testsuite/linalg.jl:3
```

Whooops, guess that simply copy/pasting this from CuArrays into GPUArrays doesn't quite work, because JLArrays don't support LinearAlgebra well enough for `ldiv!` to actually work.

@maleadt what's a reasonable way around this? Should I move this PR back to CuArrays? Is implementing `unsafe_convert` for `JLArray` a terrible idea?

**Comment by maleadt** [comment]
I'd rather add an implementation if `ldiv!`. The JLArray implementation serves as a reference of what calls you need to implement, and with this PR `LinearALgebra.ldiv!` is such an API.

**Comment by aterenin** [comment]
Added - had to fiddle with the types to avoid ambiguous method error. Tests now passing for me.

**Comment by maleadt** [comment]
Thanks. Maybe also add a test for `ldiv!` then?
bors try

**Comment by aterenin** [comment]
> Thanks. Maybe also add a test for `ldiv!` then?
> bors try

If I'm not mistaken, the current test does exactly that, since it'll call `ldiv!` for `JLArray` and compare it to the non-`JLArray` case.

**Comment by maleadt** [comment]
Yeah, I guess.

**Pull request merged**
