### PR TITLE
Move `AbstractGPUArrayStyle` to `GPUArraysCore`?

### PR DESCRIPTION
**Pull request by mcabbott**
RFC, I guess. But it would be useful to be able to dispatch on this, as for example here:

https://github.com/FluxML/Zygote.jl/blob/master/src/lib/broadcast.jl#L270

What order to tag things in may need careful thought. Does the main package needs an upper bound on the core in order not to create a clash, or can that be avoided somehow?

### CODE REVIEW

**Comment by maleadt** [comment]
> What order to tag things in may need careful thought. Does the main package needs an upper bound on the core in order not to create a clash, or can that be avoided somehow?

We're using `@reexport`, so I guess that could result in clashes. I wonder if we should better `import` the Core package instead, and reexport manually, to avoid this.

**Comment by mcabbott** [comment]
That's a good idea. 98530a1 has the definition in both packages, and we can see what CI thinks.

**Comment by maleadt** [comment]
Yeah, that's not great. I think the easiest solution is to lock GPUArrays to GPUArraysCore (i.e. edit the registry to have `=0.1` and specify `=0.2` now). What do you think?

**Comment by mcabbott** [comment]
Yes, I guess that every GPUArrays version demanding exactly one GPUArraysCore version sounds safest. 

The only downside I can see is that, if you want to make some small change to GPUArraysCore, you will need to tag a new version of the main package. But presumably there will be few such changes. And most PRs to GPUArrays won't alter GPUArraysCore at all.

This change can be GPUArraysCore 0.2, or 0.11. The argument for 0.2 is that it's not in fact a bugfix. The argument for 0.11 is that there's no need for anyone who already depends on GPUArraysCore to update their package for the new version. There seem to be 7 direct dependents now: https://juliahub.com/ui/Packages/GPUArraysCore/qiYUe/0.1.0?page=2

**Comment by maleadt** [comment]
> There seem to be 7 direct dependents now: https://juliahub.com/ui/Packages/GPUArraysCore/qiYUe/0.1.0?page=2

That happened quickly! We better stick to `0.1.1` then.

**Comment by mcabbott** [comment]
Ok, 0.1.1 it is. 

I made https://github.com/JuliaRegistries/General/pull/64447 to add a version bound. I guess that should be merged first, then GPUArraysCore tagged, then GPUArrays tagged.

**Pull request merged**
