### PR TITLE
Improve tests, typing, and overflow behavior of `norm`

### PR DESCRIPTION
**Pull request by danielwe**
* Fix test of `norm` output type, which was erroneously testing the 2-norm of CPU arrays rather than the p-norm of GPU arrays. Would have caught JuliaGPU/CUDA.jl#1444.
* Add tests with empty arrays, which seems like good practice for reduction operations. Currently failing due to #398.
* Rewrite `norm` for type stability and improved precision and overflow behavior
  * The return type is now always the real component of the floating-point promotion of the element type (e.g., ComplexF16 -> Float16 and Int32 -> Float64)
    * This is how the generic implementation in Base works, at least as a general rule
  * For Float16, perform internal computations in Float32, like `nrm2` in CUBLAS
  * Implement rescaling to avoid overflow
  * Use `norm` and `norm_sqr` rather than `abs` and `abs2`---this is what the generic implementations in Base use, presumably to accommodate more element types
  * Specialize the p = 1, 2 cases to avoid unnecessary powers
  * Use `sum` rather than `mapreduce` for these straightforward reductions, and use the function argument form off maximum/minimum to avoid the temporary array

Courtesy link to generic implementation in Base for reference: https://github.com/JuliaLang/julia/blob/24d526871d5203317fa17f93f9a4ef9fb34e8632/stdlib/LinearAlgebra/src/generic.jl#L491-L520

### CODE REVIEW

**Comment by danielwe** [comment]
Emphasizing that tests fail because of #398 since I added an empty array to this test set (they also fail on nightly if you look at the output, so no idea why it gets green checkmarks there).

Fixing mapreduce may not be sufficient for the infnorms though (the correct output isn't the neutral element of the reduction in those cases), so it may be necessary to special-case `norm` for empty arrays anyway.

**Comment by maleadt** [comment]
> Emphasizing that tests fail because of #398 since I added an empty array to this test set (they also fail on nightly if you look at the output, so no idea why it gets green checkmarks there).

That should be fixed; rebase and run tests again?

**Comment by danielwe** [comment]
Great! Still had to special case the empty case, as expected. Tests currently running should pass :crossed_fingers:

**Comment by maleadt** [comment]
CUDA.jl failure looks related?

**Comment by danielwe** [comment]
Yep, the failure is that it's now catching the bug that's fixed by JuliaGPU/CUDA.jl#1444, which was what spurred the work on this PR.

Btw., hang on for an update that gets the anti-overflow rescaling right. I figured I'd extend the tests to make sure they hit all the paths through `norm` so that the rescaling actually gets tested, and what do you know, I hadn't gotten it 100 % right.

**Comment by maleadt** [comment]
> Yep, the failure is that it's now catching the bug that's fixed by [JuliaGPU/CUDA.jl#1444](https://github.com/JuliaGPU/CUDA.jl/pull/1444), which was what spurred the work on this PR.

Ah right, of course. We can merge this then, when ready, with a test failure, and you can record the resulting git sha in CUDA.jl's git sha so that we get proper testing over there.

**Comment by danielwe** [comment]
Sounds good!

**Comment by danielwe** [comment]
Apparently, the single-precision 0.5-norm with rescaling has different behavior on windows with 1.6 and 1.7 (but not nightly) than any other configuration. I don't have a windows box to debug, but it hardly seems like the issue is with the code we're trying to test. I'll try pushing slightly less extreme tests and see if it goes away.

**Comment by maleadt** [comment]
The remaining issue is a known-to-be-flaky Statistics-related test which I haven't had the time to look into yet. So this looks good to go.

**Comment by danielwe** [comment]
Added tests for the underflow side of the rescaling as well (and improved some comments). Tests still pass on my end, but this last push doesn't seem to have triggered CI. As long as everything passes it's good to go from my side now.

**Comment by maleadt** [comment]
Done; thanks for the PR!

**Pull request merged**
