### PR TITLE
Add Base.clamp!

### PR DESCRIPTION
**Pull request by janEbert**
I ported this from my CuArrays implementation (below) so maybe there is a mistake; testing with `allowscalar(false)` works, though.
Also, I created a new file math.jl file due to `Base.clamp!` being defined in math.jl as well. Obviously, that file and the corresponding new test file are pretty empty at the moment.

```julia
function Base.clamp!(A::CuArray, low, high)
    function kernel(A, low, high)
        I = CuArrays.@cuindex A
        A[I...] = clamp(A[I...], low, high)
        return
    end
    blocks, threads = CuArrays.cudims(A)
    @cuda blocks=blocks threads=threads kernel(A, low, high)
    return A
end
```

### CODE REVIEW

**Comment by maleadt** [comment]
Looks good, thanks! Let's test:
bors try

**Comment by janEbert** [comment]
What is the issue with bors timing out? Unrelated to this?

**Comment by maleadt** [comment]
Yeah, I removed AppVeyor CI since Travis does Windows nowadays, but forgot to remove the bors configuration: https://github.com/JuliaGPU/GPUArrays.jl/commit/c9b5f992a683b0ed92e1d7b972cd2193e962ea35

**Comment by janEbert** [comment]
I see, thanks for explaining!

**Pull request merged**
