### PR TITLE
Grid-stride broadcast

### PR DESCRIPTION
**Pull request by maleadt**
Surprisingly, this is slower though (using the occupancy API's recommendation for blocks).

### CODE REVIEW

**Comment by maleadt** [comment]
I expected this to yield better performance because we're giving the GPU more work per thread, but that doesn't seem to be the case. For a simple broadcast, which the launch occupancy wants at least 1024 threads / 48 blocks:

```
(threads = 64, blocks = 262144, elements_per_thread = 1): 0.000377632
(threads = 64, blocks = 131072, elements_per_thread = 2): 0.000376584
(threads = 64, blocks = 52429, elements_per_thread = 5): 0.000377666
(threads = 64, blocks = 26215, elements_per_thread = 10): 0.000379431
(threads = 64, blocks = 5243, elements_per_thread = 50): 0.000395429
(threads = 64, blocks = 2622, elements_per_thread = 100): 0.000429447
(threads = 64, blocks = 656, elements_per_thread = 400): 0.000472881

(threads = 256, blocks = 65536, elements_per_thread = 1): 0.000377542
(threads = 256, blocks = 32768, elements_per_thread = 2): 0.000376409
(threads = 256, blocks = 13108, elements_per_thread = 5): 0.000377011
(threads = 256, blocks = 6554, elements_per_thread = 10): 0.000378
(threads = 256, blocks = 1311, elements_per_thread = 50): 0.000387118
(threads = 256, blocks = 656, elements_per_thread = 100): 0.000408212
(threads = 256, blocks = 164, elements_per_thread = 400): 0.000477594

(threads = 512, blocks = 32768, elements_per_thread = 1): 0.000379377
(threads = 512, blocks = 16384, elements_per_thread = 2): 0.00037787
(threads = 512, blocks = 6554, elements_per_thread = 5): 0.000377933
(threads = 512, blocks = 3277, elements_per_thread = 10): 0.000379647
(threads = 512, blocks = 656, elements_per_thread = 50): 0.000388141
(threads = 512, blocks = 328, elements_per_thread = 100): 0.000408506
(threads = 512, blocks = 82, elements_per_thread = 400): 0.000462272

(threads = 1024, blocks = 16384, elements_per_thread = 1): 0.000450031
(threads = 1024, blocks = 8192, elements_per_thread = 2): 0.00039061
(threads = 1024, blocks = 3277, elements_per_thread = 5): 0.000381185
(threads = 1024, blocks = 1639, elements_per_thread = 10): 0.000382585
(threads = 1024, blocks = 328, elements_per_thread = 50): 0.000395381
(threads = 1024, blocks = 164, elements_per_thread = 100): 0.000444776
(threads = 1024, blocks = 41, elements_per_thread = 400): 0.000463206
```

So the threads=1024 recommendation doesn't seem the best configuration. Only for that configuration it's advantageous to process multiple elements per thread. Maybe our data dependencies are too complex?

**Comment by maleadt** [comment]
Note that this functionality is still interesting to be able to process data that's larger than the grid.

**Comment by maleadt** [comment]
Interesting; the actual occupancy is known good for lower thread configurations:

```
julia> a .+ b;
occupancy(kernel.fun, 1024) = 1.0

julia> a .+ b;
occupancy(kernel.fun, 512) = 1.0

julia> a .+ b;
occupancy(kernel.fun, 64) = 1.0

julia> a .+ b;
occupancy(kernel.fun, 32) = 0.5
```

**Comment by maleadt** [comment]
https://github.com/cupy/cupy/pull/2827#issuecomment-567420735

**Comment by Ellipse0934** [comment]
Not surprised with the results but I do think they were worth trying. The question is what happens with complicated functions, here we have a memory access which is hundreds of cycles and compute (addition) which is presumably 1-2 ops. What happens when the compute becomes 50, 100, 200 cycles ? And even if we measure an advantage will such micro-optimizations even matter in the end ? In the data-center multiple processes might be using the card simultaneously and even in the case of a single process, multiple streams may be executing and these scenarios will mean that our optimizations on our end may end up hurting performance. The advantage will have to be pretty significant to even consider imo.

**Comment by maleadt** [comment]
> What happens when the compute becomes 50, 100, 200 cycles ?

Same thing.



> And even if we measure an advantage will such micro-optimizations even matter in the end ?

For broadcast, being such an elementary kernel, it would have.

Anyway, tuning the launch configuration with what I learned here is going to more impactful. We should also look at trying to reduce the overheads of launching an overhead, with some of the above examples that take 400us, only around 300 is spent in the kernel (even in the non-allocating case).

**Pull request merged**
