### PR TITLE
Fix UniformScaling constructor + copyto!

### PR DESCRIPTION
**Pull request by haampie**
.. and improve the tests a bit to test rectangular matrices.

Fixes the issue where `CuArray(1f0I, 3, 4)` did not deduce the element type

### CODE REVIEW

**Comment by maleadt** [comment]
bors try

**Comment by haampie** [comment]
Seems like a Travis issue "An error occurred while generating the build script."

**Comment by haampie** [comment]
Should we retry @maleadt?

**Comment by maleadt** [comment]
bors try

**Comment by maleadt** [comment]
bors d+

**Comment by haampie** [comment]
Ok... one more time

bors try

**Comment by maleadt** [comment]
I'll add you to the JuliaGPU gitlab org, that way you can selectively start/restart jobs.

**Comment by aterenin** [comment]
Thanks very much for this! My humble Gaussian process package is now one step closer to working on GPU out of the box! 🙂

Looking forward to the next release.

**Pull request merged**
