### PR TITLE
Revamp diagonal `cholesky` method

### PR DESCRIPTION
**Pull request by simsurace**
This tries to address no. 1 of #434 and also make some overall improvements.
It assumes `findfirst` is implemented for JLArrays without triggering scalar indexing. In practice, this means it won't pass tests before #436 has been merged.

### CODE REVIEW

**Comment by maleadt** [comment]
> In practice, this means it won't pass tests before #436 has been merged.

You can base PRs on top of other branches that are not master. I've rebased your PR, but there's some other CI failures that look related.

**Comment by simsurace** [comment]
The `nothing`s seem to happen with JLArrays. Unfortunately I don't think I have any means to debug this locally.

**Comment by maleadt** [comment]
> Unfortunately I don't think I have any means to debug this locally.

JLArrays is the test CPU back-end; it's available as the registered JLArrays.jl package (but also available in `lib/JLArrays`) and can also be constructed with the `jl` function (much like `cu`). You don't need any special hardware for it.

**Comment by simsurace** [comment]
It turned out to be a rather silly translation mistake. Let's see whether this does the job.

**Comment by simsurace** [comment]
Ok, this seems to do the trick.

**Comment by simsurace** [comment]
@maleadt, are there any blockers?

**Comment by maleadt** [comment]
Yeah, oneAPI CI fails, see https://github.com/JuliaGPU/GPUArrays.jl/pull/436.

(also, for future reference, please rebase instead of merging; the timeline here now includes unrelated commits)

**Comment by maleadt** [comment]
You introduced even more commits :-) I'll rebase it when I get the time to fix #436.

**Comment by simsurace** [comment]
I'm sorry, I just used the GitHub merge editor to resolve the conflicts that were reported. I don't see any additional commits in this timeline. I guess I'm unfamiliar with the way in which you manage the different branches here.
I'm used to just setting the base branch to master and merging master into the branch before making the merge, which is compatible with the GitHub interface, but presumably you are doing it differently here. Again, apologies for making your life harder than it needs to be.

**Comment by maleadt** [comment]
> I don't see any additional commits in this timeline.

There's a whole lot of unrelated commits in here, no?

image

Granted, they don't cause actual diff in the review tab, so aren't much of an issue (especially if squash merging), but they're a bit messy. Nothing to worry about, again, I'll just rebase when I fix the underlying issue 🙂

**Comment by maleadt** [comment]
Apparently you confused GitHub too, because merging #436 closed this PR... I'll open a new one

**Pull request closed without merging**
