### PR TITLE
use style dispatch in materialize

### PR DESCRIPTION
**Pull request by vchuravy**
x-ref: https://github.com/JuliaLang/julia/pull/35620

### CODE REVIEW

**Comment by maleadt** [comment]
What's the advantage of this? Tests?

**Comment by vchuravy** [comment]
`dest .= expr`,  the destination can now be anything that promotes to the right broadcast style instead of being a fixed union.

**Comment by piever** [comment]
It seems like this is actually needed to get nice interoperability between StructArrays broadcast and GPU arrays broadcast, see https://github.com/JuliaArrays/StructArrays.jl/pull/211#discussion_r803571725. A `StructArray` whose component are GPU arrays is a good example of a suitable container that is not covered by the current `copyto!` rule.

This change (plus potentially moving the `backend` function to a lightweight package like Adapt.jl to avoid taking a dependency here) should allow external packages with custom broadcast (like StructArrays) to interoperate with GPUArrays broadcast.

**Comment by vchuravy** [comment]
@piever want to take a stab at this? As you can tell I run out if time to work on it shortly after opening the PR

**Comment by N5N3** [comment]
@vchuravy I guess the following is enough?
```julia
@inline function materialize!(::Style, dest, bc::Broadcasted) where {Style<:AbstractGPUArrayStyle}
    return _copyto!(dest, instantiate(Broadcasted{Style}(bc.f, bc.args, axes(dest))))
end

@inline Base.copyto!(dest::BroadcastGPUArray, bc::Broadcasted{Nothing}) = _copyto!(dest, bc) # Keep it for ArrayConflict

@inline Base.copyto!(dest::AbstractArray, bc::Broadcasted{<:AbstractGPUArrayStyle}) = _copyto!(dest, bc)

@inline function _copyto!(dest::AbstractArray, bc::Broadcasted)
    axes(dest) == axes(bc) || Broadcast.throwdm(axes(dest), axes(bc))
    isempty(dest) && return dest
    bc′ = Broadcast.preprocess(dest, bc)
    ...
```
Local test shows no problem. Is it OK to open a new PR?

**Comment by piever** [comment]
@N5N3, I think it would be great if you could open PRs here and on StructArrays to check that everything works. I confess I am a bit out of my depth on the technicalities of the `broadcast` machinery.

**Comment by maleadt** [comment]
Superseded by https://github.com/JuliaGPU/GPUArrays.jl/pull/393 IIUC

**Pull request closed without merging**
