### PR TITLE
Add and test multiplicative identity based on uniform scaling.

### PR DESCRIPTION
**Pull request by maleadt**
Fixes JuliaGPU/CUDA.jl#897 

@albheim Does this look OK? Fixes raising a matrix by 0 using the Base implementation.

### CODE REVIEW

**Comment by albheim** [comment]
Looks good to me :+1: 

Can also close https://github.com/JuliaGPU/CUDA.jl/issues/897 if this gets merged.

**Comment by maleadt** [comment]
> Can also close [JuliaGPU/CUDA.jl#897](https://github.com/JuliaGPU/CUDA.jl/issues/897) if this gets merged.

Oh yes that's what I intended to link to. I guess we can close the Julia issue too, unless there's other suggestions on a generic approach that does not regress the case for Array.

**Comment by stevengj** [comment]
I don't think this is the right solution — as I commented [here](https://github.com/JuliaLang/julia/issues/40796#issuecomment-843304637), you probably want to return a `CuArray`

**Comment by maleadt** [comment]
> you probably want to return a `CuArray` to be analogous to the Base function

It ends up calling `CuArray{T}(I, m,n)` which _is_ a CuArray, and only uses UniformScaling to set the diagonal.

**Comment by stevengj** [comment]
You might consider overriding `Base._one`, instead, so that `oneunit` also works.

**Comment by maleadt** [comment]
Generalized the implementation to cover `oneunit` (without implementing `Base._one` though, it was easy enough to avoid extending a private interface).

**Pull request merged**
