### PR TITLE
next major release

### PR DESCRIPTION
**Pull request by SimonDanisch**

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Sorry for the delay with merging this, but I ended up adding quite a few things :

* more tests
* better performance
* vcat, hcat
* real copy support with CartesianRange
* better indexing
* properly overload fft interface
* CUFFT
* nd broadcast support
* backends share broadcast code
* better gpu_call, which also works consistently with threaded backend
* In OpenCL: better vstore/vload for  fixedsize arrays (currently NTuple + SVector are treated as fixedsize array)
* properly overload scale!
* reinterpret 
* supports broadcast with Ref(::GPUArray) now
* implements push!/resize!/splice!

This is waiting on:
https://github.com/JuliaGPU/OpenCL.jl/pull/139
https://github.com/JuliaGPU/CLFFT.jl/pull/22
https://github.com/JuliaGPU/CUDAdrv.jl/pull/52

**Comment by SimonDanisch** [comment]
And: https://github.com/JuliaLang/METADATA.jl/pull/10518

**Comment by maleadt** [comment]
Idea: why not make `build.jl` try and import CUDAnative && check `CUDAnative.configured` (see [this](https://github.com/JuliaGPU/CUDAnative.jl/blob/68ce4ef00b100e57bf502778fc6c76bded83bc76/src/CUDAnative.jl#L10-L17)) instead of the current ENV check?

**Comment by SimonDanisch** [comment]
Im going ahead and merge this, since it passes locally with CUDAnative, and I can't really debug on @maleadt machine!

**Pull request merged**
